def get_opcode(mnemonic):
    m = mnemonic.upper().strip()
    # Extract just the mnemonic token (first word) for startswith checks
    tok = m.split()[0] if m.split() else ""

    # Returns (opcode, bytes)

    # ── A ────────────────────────────────────────────────────────────
    if   tok == "ACI":   return ("CE", 2)
    elif tok == "ADC":
        if   "ADC A"  in m: return ("8F", 1)
        elif "ADC B"  in m: return ("88", 1)
        elif "ADC C"  in m: return ("89", 1)
        elif "ADC D"  in m: return ("8A", 1)
        elif "ADC E"  in m: return ("8B", 1)
        elif "ADC H"  in m: return ("8C", 1)
        elif "ADC L"  in m: return ("8D", 1)
        elif "ADC M"  in m: return ("8E", 1)
    elif tok == "ADD":
        if   "ADD A"  in m: return ("87", 1)
        elif "ADD B"  in m: return ("80", 1)
        elif "ADD C"  in m: return ("81", 1)
        elif "ADD D"  in m: return ("82", 1)
        elif "ADD E"  in m: return ("83", 1)
        elif "ADD H"  in m: return ("84", 1)
        elif "ADD L"  in m: return ("85", 1)
        elif "ADD M"  in m: return ("86", 1)
    elif tok == "ADI":   return ("C6", 2)
    elif tok == "ANA":
        if   "ANA A"  in m: return ("A7", 1)
        elif "ANA B"  in m: return ("A0", 1)
        elif "ANA C"  in m: return ("A1", 1)
        elif "ANA D"  in m: return ("A2", 1)
        elif "ANA E"  in m: return ("A3", 1)
        elif "ANA H"  in m: return ("A4", 1)
        elif "ANA L"  in m: return ("A5", 1)
        elif "ANA M"  in m: return ("A6", 1)
    elif tok == "ANI":   return ("E6", 2)

    # ── C ────────────────────────────────────────────────────────────
    elif tok == "CALL":  return ("CD", 3)
    elif tok == "CC":    return ("DC", 3)
    elif tok == "CM":    return ("FC", 3)
    elif tok == "CMA":   return ("2F", 1)
    elif tok == "CMC":   return ("3F", 1)
    elif tok == "CMP":
        if   "CMP A"  in m: return ("BF", 1)
        elif "CMP B"  in m: return ("B8", 1)
        elif "CMP C"  in m: return ("B9", 1)
        elif "CMP D"  in m: return ("BA", 1)
        elif "CMP E"  in m: return ("BB", 1)
        elif "CMP H"  in m: return ("BC", 1)
        elif "CMP L"  in m: return ("BD", 1)
        elif "CMP M"  in m: return ("BE", 1)
    elif tok == "CNC":   return ("D4", 3)
    elif tok == "CNZ":   return ("C4", 3)
    elif tok == "CP":    return ("F4", 3)
    elif tok == "CPE":   return ("EC", 3)
    elif tok == "CPI":   return ("FE", 2)
    elif tok == "CPO":   return ("E4", 3)
    elif tok == "CZ":    return ("CC", 3)

    # ── D ────────────────────────────────────────────────────────────
    elif tok == "DAA":   return ("27", 1)
    elif tok == "DAD":
        if   "DAD B"  in m: return ("09", 1)
        elif "DAD D"  in m: return ("19", 1)
        elif "DAD H"  in m: return ("29", 1)
        elif "DAD SP" in m: return ("39", 1)
    elif tok == "DCR":
        if   "DCR A"  in m: return ("3D", 1)
        elif "DCR B"  in m: return ("05", 1)
        elif "DCR C"  in m: return ("0D", 1)
        elif "DCR D"  in m: return ("15", 1)
        elif "DCR E"  in m: return ("1D", 1)
        elif "DCR H"  in m: return ("25", 1)
        elif "DCR L"  in m: return ("2D", 1)
        elif "DCR M"  in m: return ("35", 1)
    elif tok == "DCX":
        if   "DCX B"  in m: return ("0B", 1)
        elif "DCX D"  in m: return ("1B", 1)
        elif "DCX H"  in m: return ("2B", 1)
        elif "DCX SP" in m: return ("3B", 1)
    elif tok == "DI":    return ("F3", 1)

    # ── E ────────────────────────────────────────────────────────────
    elif tok == "EI":    return ("FB", 1)

    # ── H ────────────────────────────────────────────────────────────
    elif tok == "HLT":   return ("76", 1)

    # ── I ────────────────────────────────────────────────────────────
    elif tok == "IN":    return ("DB", 2)
    elif tok == "INR":
        if   "INR A"  in m: return ("3C", 1)
        elif "INR B"  in m: return ("04", 1)
        elif "INR C"  in m: return ("0C", 1)
        elif "INR D"  in m: return ("14", 1)
        elif "INR E"  in m: return ("1C", 1)
        elif "INR H"  in m: return ("24", 1)
        elif "INR L"  in m: return ("2C", 1)
        elif "INR M"  in m: return ("34", 1)
    elif tok == "INX":
        if   "INX B"  in m: return ("03", 1)
        elif "INX D"  in m: return ("13", 1)
        elif "INX H"  in m: return ("23", 1)
        elif "INX SP" in m: return ("33", 1)

    # ── J ────────────────────────────────────────────────────────────
    elif tok == "JC":    return ("DA", 3)
    elif tok == "JM":    return ("FA", 3)
    elif tok == "JMP":   return ("C3", 3)
    elif tok == "JNC":   return ("D2", 3)
    elif tok == "JNZ":   return ("C2", 3)
    elif tok == "JP":    return ("F2", 3)
    elif tok == "JPE":   return ("EA", 3)
    elif tok == "JPO":   return ("E2", 3)
    elif tok == "JZ":    return ("CA", 3)

    # ── L ────────────────────────────────────────────────────────────
    elif tok == "LDA":   return ("3A", 3)
    elif tok == "LDAX":
        if   "LDAX B" in m: return ("0A", 1)
        elif "LDAX D" in m: return ("1A", 1)
    elif tok == "LHLD":  return ("2A", 3)
    elif tok == "LXI":
        if   "LXI B"  in m: return ("01", 3)
        elif "LXI D"  in m: return ("11", 3)
        elif "LXI H"  in m: return ("21", 3)
        elif "LXI SP" in m: return ("31", 3)

    # ── M ────────────────────────────────────────────────────────────
    elif tok == "MOV":
        if   "MOV A, A" in m: return ("7F", 1)
        elif "MOV A, B" in m: return ("78", 1)
        elif "MOV A, C" in m: return ("79", 1)
        elif "MOV A, D" in m: return ("7A", 1)
        elif "MOV A, E" in m: return ("7B", 1)
        elif "MOV A, H" in m: return ("7C", 1)
        elif "MOV A, L" in m: return ("7D", 1)
        elif "MOV A, M" in m: return ("7E", 1)
        elif "MOV B, A" in m: return ("47", 1)
        elif "MOV B, B" in m: return ("40", 1)
        elif "MOV B, C" in m: return ("41", 1)
        elif "MOV B, D" in m: return ("42", 1)
        elif "MOV B, E" in m: return ("43", 1)
        elif "MOV B, H" in m: return ("44", 1)
        elif "MOV B, L" in m: return ("45", 1)
        elif "MOV B, M" in m: return ("46", 1)
        elif "MOV C, A" in m: return ("4F", 1)
        elif "MOV C, B" in m: return ("48", 1)
        elif "MOV C, C" in m: return ("49", 1)
        elif "MOV C, D" in m: return ("4A", 1)
        elif "MOV C, E" in m: return ("4B", 1)
        elif "MOV C, H" in m: return ("4C", 1)
        elif "MOV C, L" in m: return ("4D", 1)
        elif "MOV C, M" in m: return ("4E", 1)
        elif "MOV D, A" in m: return ("57", 1)
        elif "MOV D, B" in m: return ("50", 1)
        elif "MOV D, C" in m: return ("51", 1)
        elif "MOV D, D" in m: return ("52", 1)
        elif "MOV D, E" in m: return ("53", 1)
        elif "MOV D, H" in m: return ("54", 1)
        elif "MOV D, L" in m: return ("55", 1)
        elif "MOV D, M" in m: return ("56", 1)
        elif "MOV E, A" in m: return ("5F", 1)
        elif "MOV E, B" in m: return ("58", 1)
        elif "MOV E, C" in m: return ("59", 1)
        elif "MOV E, D" in m: return ("5A", 1)
        elif "MOV E, E" in m: return ("5B", 1)
        elif "MOV E, H" in m: return ("5C", 1)
        elif "MOV E, L" in m: return ("5D", 1)
        elif "MOV E, M" in m: return ("5E", 1)
        elif "MOV H, A" in m: return ("67", 1)
        elif "MOV H, B" in m: return ("60", 1)
        elif "MOV H, C" in m: return ("61", 1)
        elif "MOV H, D" in m: return ("62", 1)
        elif "MOV H, E" in m: return ("63", 1)
        elif "MOV H, H" in m: return ("64", 1)
        elif "MOV H, L" in m: return ("65", 1)
        elif "MOV H, M" in m: return ("66", 1)
        elif "MOV L, A" in m: return ("6F", 1)
        elif "MOV L, B" in m: return ("68", 1)
        elif "MOV L, C" in m: return ("69", 1)
        elif "MOV L, D" in m: return ("6A", 1)
        elif "MOV L, E" in m: return ("6B", 1)
        elif "MOV L, H" in m: return ("6C", 1)
        elif "MOV L, L" in m: return ("6D", 1)
        elif "MOV L, M" in m: return ("6E", 1)
        elif "MOV M, A" in m: return ("77", 1)
        elif "MOV M, B" in m: return ("70", 1)
        elif "MOV M, C" in m: return ("71", 1)
        elif "MOV M, D" in m: return ("72", 1)
        elif "MOV M, E" in m: return ("73", 1)
        elif "MOV M, H" in m: return ("74", 1)
        elif "MOV M, L" in m: return ("75", 1)
    elif tok == "MVI":
        if   "MVI A" in m: return ("3E", 2)
        elif "MVI B" in m: return ("06", 2)
        elif "MVI C" in m: return ("0E", 2)
        elif "MVI D" in m: return ("16", 2)
        elif "MVI E" in m: return ("1E", 2)
        elif "MVI H" in m: return ("26", 2)
        elif "MVI L" in m: return ("2E", 2)
        elif "MVI M" in m: return ("36", 2)

    # ── N ────────────────────────────────────────────────────────────
    elif tok == "NOP":   return ("00", 1)

    # ── O ────────────────────────────────────────────────────────────
    elif tok == "ORA":
        if   "ORA A"  in m: return ("B7", 1)
        elif "ORA B"  in m: return ("B0", 1)
        elif "ORA C"  in m: return ("B1", 1)
        elif "ORA D"  in m: return ("B2", 1)
        elif "ORA E"  in m: return ("B3", 1)
        elif "ORA H"  in m: return ("B4", 1)
        elif "ORA L"  in m: return ("B5", 1)
        elif "ORA M"  in m: return ("B6", 1)
    elif tok == "ORI":   return ("F6", 2)
    elif tok == "OUT":   return ("D3", 2)

    # ── P ────────────────────────────────────────────────────────────
    elif tok == "PCHL":  return ("E9", 1)
    elif tok == "POP":
        if   "POP B"   in m: return ("C1", 1)
        elif "POP D"   in m: return ("D1", 1)
        elif "POP H"   in m: return ("E1", 1)
        elif "POP PSW" in m: return ("F1", 1)
    elif tok == "PUSH":
        if   "PUSH B"   in m: return ("C5", 1)
        elif "PUSH D"   in m: return ("D5", 1)
        elif "PUSH H"   in m: return ("E5", 1)
        elif "PUSH PSW" in m: return ("F5", 1)

    # ── R ────────────────────────────────────────────────────────────
    elif tok == "RAL":   return ("17", 1)
    elif tok == "RAR":   return ("1F", 1)
    elif tok == "RC":    return ("D8", 1)
    elif tok == "RET":   return ("C9", 1)
    elif tok == "RIM":   return ("20", 1)
    elif tok == "RLC":   return ("07", 1)
    elif tok == "RM":    return ("F8", 1)
    elif tok == "RNC":   return ("D0", 1)
    elif tok == "RNZ":   return ("C0", 1)
    elif tok == "RP":    return ("F0", 1)
    elif tok == "RPE":   return ("E8", 1)
    elif tok == "RPO":   return ("E0", 1)
    elif tok == "RRC":   return ("0F", 1)
    elif tok == "RST":
        if   "RST 0"  in m: return ("C7", 1)
        elif "RST 1"  in m: return ("CF", 1)
        elif "RST 2"  in m: return ("D7", 1)
        elif "RST 3"  in m: return ("DF", 1)
        elif "RST 4"  in m: return ("E7", 1)
        elif "RST 5"  in m: return ("EF", 1)
        elif "RST 6"  in m: return ("F7", 1)
        elif "RST 7"  in m: return ("FF", 1)
    elif tok == "RZ":    return ("C8", 1)

    # ── S ────────────────────────────────────────────────────────────
    elif tok == "SBB":
        if   "SBB A"  in m: return ("9F", 1)
        elif "SBB B"  in m: return ("98", 1)
        elif "SBB C"  in m: return ("99", 1)
        elif "SBB D"  in m: return ("9A", 1)
        elif "SBB E"  in m: return ("9B", 1)
        elif "SBB H"  in m: return ("9C", 1)
        elif "SBB L"  in m: return ("9D", 1)
        elif "SBB M"  in m: return ("9E", 1)
    elif tok == "SBI":   return ("DE", 2)
    elif tok == "SHLD":  return ("22", 3)
    elif tok == "SIM":   return ("30", 1)
    elif tok == "SPHL":  return ("F9", 1)
    elif tok == "STA":   return ("32", 3)
    elif tok == "STAX":
        if   "STAX B" in m: return ("02", 1)
        elif "STAX D" in m: return ("12", 1)
    elif tok == "STC":   return ("37", 1)
    elif tok == "SUB":
        if   "SUB A"  in m: return ("97", 1)
        elif "SUB B"  in m: return ("90", 1)
        elif "SUB C"  in m: return ("91", 1)
        elif "SUB D"  in m: return ("92", 1)
        elif "SUB E"  in m: return ("93", 1)
        elif "SUB H"  in m: return ("94", 1)
        elif "SUB L"  in m: return ("95", 1)
        elif "SUB M"  in m: return ("96", 1)
    elif tok == "SUI":   return ("D6", 2)

    # ── X ────────────────────────────────────────────────────────────
    elif tok == "XCHG":  return ("EB", 1)
    elif tok == "XRA":
        if   "XRA A"  in m: return ("AF", 1)
        elif "XRA B"  in m: return ("A8", 1)
        elif "XRA C"  in m: return ("A9", 1)
        elif "XRA D"  in m: return ("AA", 1)
        elif "XRA E"  in m: return ("AB", 1)
        elif "XRA H"  in m: return ("AC", 1)
        elif "XRA L"  in m: return ("AD", 1)
        elif "XRA M"  in m: return ("AE", 1)
    elif tok == "XRI":   return ("EE", 2)
    elif tok == "XTHL":  return ("E3", 1)

    return ("None", 0)

